### ISSUE TITLE
Multiple values per unit time

### ISSUE THREAD

**Issue by bmo-at** [innius/grafana-simple-grpc-datasource#2]
Hi!

So I've been using your plugin to display data from our API, with a gRPC endpoint that I wrote according to the protobuf file.
One limitation I have come across is that given any metric, you can only ever return one value per timestamp.
The reason this is a limitation is that some APIs including ours return mutliple different datapoints per timestamp.
Consider the following use case: 
An API that returns the state of webrequests. So for a given time span and a resolution it returns e.g. 5 minute buckets in which a set of http status codes might have occured, the corresponding data in JSON might look like this:
```json
{ 
    "points": [
        {
            "timestamp": 1637155203278,
            "data": {
                "200": 589,
                "404": 23,
                ...
            }
        }, 
        {
            "timestamp": 1637154903278,
            "data": {
                "200": 367,
                "404": 16,
                "500": 4,
                ...
            }
        },
        ...
    ]
}
``` 
Now I'd like to send that over grpc and ideally have the plugin accept an ID of some sort (probably a string) in a MetricValue so that instead of the table view looking like this:
![image](https://user-images.githubusercontent.com/5568767/142209394-56ddc761-7b7b-49d9-8f5a-79f1da64e4d9.png)
It could look like this:
![image](https://user-images.githubusercontent.com/5568767/142209481-879559ea-8509-4e9e-8eca-e30133a2b894.png)

One way around this would be to add queries for every status code but that would be a lot and making an exhaustive list isn't fun.
With a few changes to the proto file and the backend server I managed to get this running on my fork.
The question is, is there any will to consider this change? I'd be providing an implementation of it to merge upstream, if the change is welcome.

Greetings,
Jan-Robin Aumann

**Comment by rvdwijngaard** [comment]
Hello, 

Just to verify if I understood you correctly. 

Summary: a metric returns a single value but you want multiple values to be returned by the same metric. Is that correct? We have been thinking about this before. The context was a bit different at that moment because we considered to accept multiple metrics in one request. We dropped that idea because it was adding too much complexity to the system. 

In order to achieve this the API has to be changed to something like this: 
```
rpc GetMetricHistory (GetMetricHistoryRequest) returns (GetMetricHistoryResponse) {}
```
change this into something like this
```
message Metric {
  string id = 1;
}

message Datapoint {
  // The timestamp date, in seconds, in the Unix epoch format.
  int64 timestamp = 1;

  // The current metric value.
  MetricValue value = 2;
}

// GetMetricAggregateResponse is the result of a MetricHistory query
message GetMetricHistoryResponse {
  message Result {
    Metric metric = 1;
    repeated Datapoint values = 2;
  }
  // Result is the query result which may include multiple metrics
  repeated Result result = 1;

  // The token for the next set of results, or null if there are no additional results.
  string nextToken = 2;
}
```
One of the things which is getting a bit complicated is how to handle the nextToken (for pagination). Currently the grafana internal API (between frontend and backend plugin) can only handle one `nextToken`.

**Comment by bmo-at** [comment]
I think you understood me correctly.
Though I'd suggest a different approach, which I have implemented and tested in my [fork](https://github.com/bmo-at/grafana-simple-grpc-datasource/commit/b0391fbce8037ad03d0082858c8a40e97cd5b4b2):
I changed the MetricHistoryValue and the GetMetricValueResponse such that they now contain a timestamp (as before) and instead of a single MetricValue an array of them. I also gave each MetricValue an id of type string to identify them by.

```proto
message MetricValue {
    double doubleValue = 1;
    string id = 2;
}
...
message MetricHistoryValue {
    // The timestamp date, in seconds, in the Unix epoch format.
    int64 timestamp = 1;
    // Contains asset property value information
    repeated MetricValue values = 2;
}
...
message GetMetricValueResponse {
    // The timestamp date, in seconds, in the Unix epoch format.
    int64 timestamp = 1;

    // The current metric value.
    repeated MetricValue values = 2;
}
```

I then generated the backend go code and changed it so it can deal with the id's and arrays of MetricValue's.
It's a reasonably small change though it does break API compat with previous versions of the plugin.

**Comment by bmo-at** [comment]
What this the leads to is dashboards like this:
![image](https://user-images.githubusercontent.com/5568767/144245430-2fb2626f-70ae-49dd-8c5e-e995b5a8cbd7.png)
Here you can see that for every point in time, we have Multiple MetricValues with different id's (timed out, initialized, etc.) and a coresponding doubleValue for that particular id (This dashboard visualizes the results of VoIP calls).

**Comment by rvdwijngaard** [comment]
This is actually a very good change; I would love to have this in the official plugin. Like you pointed out it breaks the API.

**Comment by bmo-at** [comment]
That's great to hear! I have put in a pull request at #3 with my changes as described above and based at the current HEAD of master.

**Comment by rvdwijngaard** [comment]
Hi @bmo-at, 

Today I have been working on a new version of the new backend API for this plugin. I am not convinced it is correct to change the signature of the API according to your proposal. I have been prototyping a bit and adding this Id attribute to the timeseries makes the API hard to implement. In addition to this it increases the size of the payload significantly because this field is repeated for each timestamped value. In my test case the payload size almost doubles.

Returning multiple frames seems to have a much better fit though: change the query configuration in such a way that it becomes possible to select multiple metrics in one query. Each query gets it's own data frame. 
![Screenshot from 2022-01-24 15-58-06](https://user-images.githubusercontent.com/7237796/150806893-f0e52a23-a9a2-41af-b363-55120cdeb695.png)
![Screenshot from 2022-01-24 15-57-57](https://user-images.githubusercontent.com/7237796/150806900-ff653e82-3189-4a09-b8ac-6a2fb4ba9055.png)

Would this also solve your case?

**Comment by bmo-at** [comment]
Hi @rvdwijngaard,
let me adress the last question first, Unfortunately, that does not solve my case. Going back to why: 
Imagine a service providing metrics about requests to a web server.
The metric in this case could be status codes. With the current API, how would you send back a meaningful reply to the plugin? Multiple frames don't address the fact that we somehow need to label the different status codes such that they can be shown in the plugin. The only way this can currently be achieved (that I can think of) is by further specifying the metrics to something like "status_codes_404" instead of "status_codes", meaning when defining a query I'd have to provide an exhaustive list of the status codes I want to receive.
This seems weird to me. The server knows what data is there, so a field in the response where this knowledge can be transmitted seems worthwhile to me.
I'm not saying my implementation is the be-all-and-end-all and the solution to all problems. In fact I'm sure if payload size id of concern that this could definitely be optimized. But leaving it out entirely seems like an extreme solution.

**Comment by rvdwijngaard** [comment]
Hello @bmo-at, 
Thanks for your comments. I agree with what you say. I made a proposal of a new API. There is currently a temporary branch with the proposed changes. I don't want to break the current API. In addition I propose to add a new enhanced API which is aligned with the grafana data frame API and provides flexibility to add multiple frames and within a frame multiple fields. In addition it supports labels. I believe this is sufficient to cover your case. Please checkout this branch, especially the [v2 protobuf](https://github.com/innius/grafana-simple-grpc-datasource/blob/feat/support_v2_api/pkg/proto/v2/apiv2.proto) definition. 

Please note this branch is a temporary branch and might disappear in the future.

**Comment by rvdwijngaard** [comment]
I think I need to add a short explanation. 
Let's take the `GetMetricHistory` API as an example (this API is almost identical to `GetMetricAggregate`)
The request has been provided with multiple metrics (which enables multiple metrics to be specified in one query). 
```
message GetMetricHistoryRequest {
  repeated Dimension dimensions = 3;
  repeated string metrics = 4;
  int64 startDate = 5;
  int64 endDate = 6;
  int64 maxItems = 7;
  TimeOrdering timeOrdering = 8;
  string startingToken = 9;
}
```
The response is changed to: 
```
message GetMetricHistoryResponse {
  repeated Frame frames = 1;

  string nextToken = 2;
}
```
The definition of `Frame` is 
```
message Frame {
  string metric = 1;

  repeated google.protobuf.Timestamp timestamps = 2;

  repeated Field fields = 3; 
}
```
As you can see this structure has multiple fields. Each field has it's own list of values. 
```
message Field {
  string name = 1;

  repeated Label labels = 2;

  config config = 3;

  repeated double values = 4;
}
```
An example of an implementation can be found in our [sample grpc server](https://bitbucket.org/innius/sample-grpc-server/src/fcbec56db58a1ee2fc1acda7948b94918d69c34f/server/v2/server.go)

**Comment by bmo-at** [comment]
Hi @rvdwijngaard, 
sorry for the late reply, I wanted to take my time and really dive into your changes.
I think this would be a terrific change and cover all my previously mentioned concerns.
Beyond that I think aligning it with grafanas data frame api is a good course of action.
Thank you in advance for this effort!
If you need any help implementing I'd be more than happy to assist in any way possible.

**Comment by rvdwijngaard** [comment]
Hello @bmo-at,

Thanks for your comments. Glad to hear you appreciate this change. I think this change is almost finished except some minor changes. One of the things I am struggling with right now is that this change introduced a breaking change which I would like to avoid. I managed to keep backend logic compatible by allowing different implementations of the same backend. The frontend definition of a query has changed because it now supports an array of metrics (instead of a single metric per query). As a result dashboards which are already configured will stop working after deploying plugin version with these changes. 

I see a few options: 
- accept the breaking change and add a warning note to the README.md
- convert the data automatically 
- keep it compatible (i.e. support both a single metric definition and an array of metrics

The third option seems the best option to me but it has a disadvantage because it clutters the code with deprecated attributes. 

Do you see other options?

**Comment by bmo-at** [comment]
I don't see other options but I'd advocate for option 2 unless you have already discovered that it is impractical/impossible.
I'd include a message in the README/release notes that conversion *might* be unsuccessful and people should watch out.
I'll be honest I am not very experienced in React but wouldnt it be possible to check for the contents of the value/values field for the metric selection and if at isn't already a Metric[] convert it on the fly?

**Comment by rvdwijngaard** [comment]
thanks for your suggestions. That was exactly what I meant. I have implemented some logic to convert on the fly. I've merged all changes into the master.

**Comment by bmo-at** [comment]
I've reimplemented my endpoint I made for the plugin now with the v2 API and boy is this thing great.
Getting reflection to work was a little bit of a pain, but overall it went well.
Hats off to you @rvdwijngaard, the design you landed on for v2 is pretty much perfect. It aligns great with Grafanas API and implementing for it honestly has made my code much simpler and easier to read.
Mind you, this is compared to my implementation based on my hackjob of a first draft of v2 but I have to say you really took this and turned it into something very useful.
Thanks again, can't wait for this to be released!
